language: node_js
node_js:
- '10.16'
script:
- npm ci
stages:
- name: test
- name: build
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    script: npm run test
  - stage: build
    script: npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    repo: chgdev/datetimeutils
    branch: master
